### ISSUE TITLE
Not working with s3ql

### ISSUE THREAD

**Issue by D4rk4** [storj/gateway-st#8]
FS creating sucessfully with comang like:
```mkfs.s3ql --cachedir=/var/cache/s3ql --backend-options no-ssl  s3c://127.0.0.1:7777/storage/next/```

But I can't mount this fs with command like:
```
mount.s3ql \
        --cachedir /var/cache/s3ql --backend-options no-ssl --compress bzip2-6 \
        --keep-cache --cachesize 33554432 --metadata-upload-interval 300 --allow-other \
        s3c://127.0.0.1:7777/storage/next/ /srv/storage/next
```

Got error on gateway side:
```{
  "error": "uplink: SetupProject error: prefix should end with slash",
  "errorVerbose": "uplink: SetupProject error: prefix should end with slash\n\tstorj.io/uplink/private/metainfo/kvmetainfo.(*DB).ListObjectsExtended:300\n\tstorj.io/uplink.(*ObjectIterator).loadNext:97\n\tstorj.io/uplink.(*ObjectIterator).Next:76\n\tstorj.io/gateway/miniogw.(*gatewayLayer).ListObjects:276\n\tstorj.io/gateway/miniogw.(*layerLogging).ListObjects:94\n\tgithub.com/minio/minio/cmd.objectAPIHandlers.ListObjectsV1Handler:340\n\tnet/http.HandlerFunc.ServeHTTP:2007\n\tgithub.com/minio/minio/cmd.httpTraceAll.func1:341\n\tnet/http.HandlerFunc.ServeHTTP:2007\n\tgithub.com/minio/minio/cmd.collectAPIStats.func1:376\n\tnet/http.HandlerFunc.ServeHTTP:2007\n\tgithub.com/gorilla/mux.(*Router).ServeHTTP:212\n\tgithub.com/minio/minio/cmd.customHeaderHandler.ServeHTTP:748\n\tgithub.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP:763\n\tgithub.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP:624\n\tgithub.com/minio/minio/cmd.requestValidityHandler.ServeHTTP:608\n\tgithub.com/minio/minio/cmd.httpStatsHandler.ServeHTTP:544\n\tgithub.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP:68\n\tgithub.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP:93\n\tgithub.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP:51\n\tgithub.com/minio/minio/cmd.redirectHandler.ServeHTTP:247\n\tgithub.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP:315\n\tgithub.com/minio/minio/cmd.cacheControlHandler.ServeHTTP:274\n\tgithub.com/minio/minio/cmd.timeValidityHandler.ServeHTTP:385\n\tgithub.com/rs/cors.(*Cors).Handler.func1:207\n\tnet/http.HandlerFunc.ServeHTTP:2007\n\tgithub.com/minio/minio/cmd.resourceHandler.ServeHTTP:525\n\tgithub.com/minio/minio/cmd.authHandler.ServeHTTP:449\n\tgithub.com/minio/minio/cmd.sseTLSHandler.ServeHTTP:798\n\tgithub.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP:136\n\tgithub.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP:780\n\tgithub.com/minio/minio/cmd/http.(*Server).Start.func1:104\n\tnet/http.HandlerFunc.ServeHTTP:2007\n\tnet/http.serverHandler.ServeHTTP:2802\n\tnet/http.(*conn).serve:1890"
}
```
 Gateway v1.0.1 
 S3QL 3.3.2+dfsg-1~bpo10+1

**Comment by D4rk4** [comment]
```
API: ListObjectsV1(bucket=storage)
Time: 18:29:56 UTC 04/08/2020
DeploymentID: 6fa86b04-cd9d-4539-9c75-f9f6dd967cd6
RequestID: 1603EBA6F23914F9
RemoteHost: 127.0.0.1
Host: 127.0.0.1:7777
Error: uplink: SetupProject error: prefix should end with slash
       4: /go/pkg/mod/github.com/minio/minio@v0.0.0-20200306214424-88ae0f119610/cmd/api-errors.go:1786:cmd.toAPIErrorCode()                                                 
       3: /go/pkg/mod/github.com/minio/minio@v0.0.0-20200306214424-88ae0f119610/cmd/api-errors.go:1811:cmd.toAPIError()                                                     
       2: /go/pkg/mod/github.com/minio/minio@v0.0.0-20200306214424-88ae0f119610/cmd/bucket-handlers-listobjects.go:342:cmd.objectAPIHandlers.ListObjectsV1Handler()         
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

**Comment by egonelbre** [comment]
Given a key structure:
```
hello/alpha/file.txt
hello/alpha-alpha/file.txt
hello/beta/file.txt
```

And prefix `hello/alpha`, it would end up mounting (this would be the case for AWS S3 as well):

```
/file.txt
-alpha/file.txt
```

I'm not sure whether this is a bug in s3ql, configuration or something else.

**Comment by D4rk4** [comment]
As I see when i'm creating new FS, S3QL creating files:
```s3ql_seq_no_1586371276 s3ql_metadata```

And when I'm trying mount FS S3QL send LIST request to backend `LIST s3ql_seq_no_ ` and expecting recieve _list of seq_no_ file(s). But in case of using **Storj S3** gw this requests don't return anything, because LIST requests not ended with slash is forbidden.

**Comment by D4rk4** [comment]
Okay version 1.0.4 now just crashing S3QL, because gateway send unexpected message:
```
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==3.3.2', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib/s3ql/s3ql/mount.py", line 128, in main
    (param, db) = get_metadata(backend, cachepath)
  File "/usr/lib/s3ql/s3ql/mount.py", line 359, in get_metadata
    seq_no = get_seq_no(backend)
  File "/usr/lib/s3ql/s3ql/common.py", line 47, in get_seq_no
    seq_nos = list(backend.list('s3ql_seq_no_'))
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 235, in list
    (els, page_token) = self._list_page(prefix, page_token)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 250, in _list_page
    resp = self._do_request('GET', '/', query_string=query_string)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 529, in _do_request
    self._parse_error_response(resp)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 563, in _parse_error_response
    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)
s3ql.backends.s3c.S3Error: InvalidArgument: prefix should end with slash
```

**Comment by kaloyan-raev** [comment]
@D4rk4 I installed S3QL and debugged it to see why it's failing.

When executing the `mount.s3ql` command, the listing request to the backend is passed with the prefix `next/s3ql_seq_no_`.

This is an attempt to list all files that start with `s3ql_seq_no_`. For example, I have such a file: `s3ql_seq_no_1586791624`.

Currently, we support only prefixes that are full path components, i.e.
- We can list with the prefix `next/s3ql_seq_no_1586791624/`
- We cannot list the prefix `next/s3ql_seq_no_`

Therefore, we made the check to explicitly require the trailing slash in prefixes, so it is more obvious that we currently do not support prefixes with partial path components.

We have the this feature in our backlog, but we are not there yet. Until we implement it, S3QL won't work properly.

**Comment by D4rk4** [comment]
@kaloyan-raev It's mean, now Storj is not usable for business and enterprise, because no usable FUSE bindings. May you prioritize this feature?

**Comment by kaloyan-raev** [comment]
@D4rk4 We have successfully used Rclone with the S3 Gateway for mounting buckets with FUSE. I recommend trying it out. https://rclone.org

First, you need to config a new backend of type `Minio` to the S3 Gateway:
```
rclone config
```
Then you can mount the bucket:
```
rclone mount us-central-1:mybucket /mnt/mybucket --vfs-cache-mode full
```
where:
- `us-central-1` is the name of the configured backend with the `rclone config` command.
- `mybucket` is the name of the Tardigrade bucket
- `/mnt/mybucket` is the location on the filesystem to mount to
- `--vfs-cache-mode full` switches to full caching mode, which disables read chunking, because it does not work well with the S3 gateway.

We are also in progress of developing a native integration for Rclone, so it can be used without S3 Gateway as a middle-man: https://github.com/rclone/rclone. We are polishing it. Hopefully, we will announce it soon with proper documentation.

**Comment by D4rk4** [comment]
@kaloyan-raev thx you for suggestion, I'm setup rclone FUSE mount, but when I'm started copying files, i'm observe IO is stuck, and i'm got error on GW side: `2020-04-14T23:17:05.509Z        ERROR   gateway error:  {"error": "Not Implemented"}`

Look like rclone is not an option.

**Comment by kaloyan-raev** [comment]
@D4rk4 Could you include the full stack of the error, so we can see which method is not implemented?

Could you give details about how exactly you copy the files?

**Comment by D4rk4** [comment]
Only this in gw logs:
```
2020-04-15T09:01:13.697Z        DEBUG   ecclient        Upload to storage node failed   {"Node ID": "12QaWzfm17t7hEEdjouS6f9j6VDpMi3NNYYsSkXqiLAmokG3Jiw", "error": "protocol: expected piece hash; context canceled", "errorVerbose": "group:\n--- protocol: expected piece hash\n\tstorj.io/uplink/private/piecestore.(*Upload).Commit:229\n\tstorj.io/uplink/private/piecestore.(*BufferedUpload).Commit:45\n\tstorj.io/uplink/private/piecestore.(*LockingUpload).Commit:105\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece.func3:237\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece:267\n\tstorj.io/uplink/private/ecclient.(*ecClient).Put.func1:113\n--- context canceled"}
2020-04-15T09:01:13.697Z        DEBUG   ecclient        Upload to storage node failed   {"Node ID": "1TfCf4ioHrxbwDz2yaRvukmKZJE1LnkPNJXQGgcM9y6QJXxqrh", "error": "protocol: expected piece hash; context canceled", "errorVerbose": "group:\n--- protocol: expected piece hash\n\tstorj.io/uplink/private/piecestore.(*Upload).Commit:229\n\tstorj.io/uplink/private/piecestore.(*BufferedUpload).Commit:45\n\tstorj.io/uplink/private/piecestore.(*LockingUpload).Commit:105\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece.func3:237\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece:267\n\tstorj.io/uplink/private/ecclient.(*ecClient).Put.func1:113\n--- context canceled"}
2020-04-15T09:01:13.698Z        DEBUG   ecclient        Upload to storage node failed   {"Node ID": "14piRQap9rfhsGiChpWXLSpihys2NuwPC8sYiMFgAbx7U6995g", "error": "protocol: expected piece hash; context canceled", "errorVerbose": "group:\n--- protocol: expected piece hash\n\tstorj.io/uplink/private/piecestore.(*Upload).Commit:229\n\tstorj.io/uplink/private/piecestore.(*BufferedUpload).Commit:45\n\tstorj.io/uplink/private/piecestore.(*LockingUpload).Commit:105\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece.func3:237\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece:267\n\tstorj.io/uplink/private/ecclient.(*ecClient).Put.func1:113\n--- context canceled"}
2020-04-15T09:01:13.698Z        DEBUG   ecclient        Upload to storage node failed   {"Node ID": "116WEQGfuiXX6P5VybNBG9EkdAf5q2BkEPSLyqMwNfEPLWQx3g", "error": "protocol: expected piece hash; context canceled", "errorVerbose": "group:\n--- protocol: expected piece hash\n\tstorj.io/uplink/private/piecestore.(*Upload).Commit:229\n\tstorj.io/uplink/private/piecestore.(*BufferedUpload).Commit:45\n\tstorj.io/uplink/private/piecestore.(*LockingUpload).Commit:105\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece.func3:237\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece:267\n\tstorj.io/uplink/private/ecclient.(*ecClient).Put.func1:113\n--- context canceled"}
2020-04-15T09:01:13.698Z        DEBUG   ecclient        Upload to storage node failed   {"Node ID": "1ie9bjYdupu5S13eDqcV827P97XyGMyK1SuNbw5iYyGgMx7KDJ", "error": "protocol: expected piece hash; context canceled", "errorVerbose": "group:\n--- protocol: expected piece hash\n\tstorj.io/uplink/private/piecestore.(*Upload).Commit:229\n\tstorj.io/uplink/private/piecestore.(*BufferedUpload).Commit:45\n\tstorj.io/uplink/private/piecestore.(*LockingUpload).Commit:105\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece.func3:237\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece:267\n\tstorj.io/uplink/private/ecclient.(*ecClient).Put.func1:113\n--- context canceled"}
2020-04-15T09:01:13.698Z        DEBUG   ecclient        Upload to storage node failed   {"Node ID": "1eV4S4Pf3XHW2u7vsDWuXSF9AVucsfuRwDHbpT3rXxK5BJrQDa", "error": "protocol: expected piece hash; context canceled", "errorVerbose": "group:\n--- protocol: expected piece hash\n\tstorj.io/uplink/private/piecestore.(*Upload).Commit:229\n\tstorj.io/uplink/private/piecestore.(*BufferedUpload).Commit:45\n\tstorj.io/uplink/private/piecestore.(*LockingUpload).Commit:105\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece.func3:237\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece:267\n\tstorj.io/uplink/private/ecclient.(*ecClient).Put.func1:113\n--- context canceled"}
2020-04-15T09:01:13.704Z        DEBUG   ecclient        Upload to storage node failed   {"Node ID": "1ygsDR8YSZHnwny5o2L6MUzQZcjojkUHFLk5ddXYatxA2xneME", "error": "protocol: expected piece hash; context canceled", "errorVerbose": "group:\n--- protocol: expected piece hash\n\tstorj.io/uplink/private/piecestore.(*Upload).Commit:229\n\tstorj.io/uplink/private/piecestore.(*BufferedUpload).Commit:45\n\tstorj.io/uplink/private/piecestore.(*LockingUpload).Commit:105\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece.func3:237\n\tstorj.io/uplink/private/ecclient.(*ecClient).PutPiece:267\n\tstorj.io/uplink/private/ecclient.(*ecClient).Put.func1:113\n--- context canceled"}
2020-04-15T09:01:14.442Z        ERROR   gateway error:  {"error": "Not Implemented"}
```

I'm trying mount with 
```rclone mount storage /srv/sj/storage/ --vfs-cache-mode full --cache-dir /var/cache/sj/storage --allow-other```

And I'm using syncthing for syncing files to Storj mount location.

**Comment by kaloyan-raev** [comment]
@D4rk4 Could you run the gateway with `--log.level debug`? Hopefully, we will see more defails below "Not implemented".

**Comment by kaloyan-raev** [comment]
Or I just noticed there DEBUG level log...

**Comment by D4rk4** [comment]
Already:
```
grep log .local/share/storj/gateway/config.yaml | grep -v \#
log.development: true
log.level: debug

```

**Comment by D4rk4** [comment]
Maybe better option - implement native backend for widely used S3QL 🤔

**Comment by kaloyan-raev** [comment]
S3QL is in Python. While Rclone is in Go. We have a Go library while we don't have a Python one yet. Also, we have other use cases for Rclone beyond FUSE mounting.

I am now trying to see if I can reproduce the issue with syncthing.

**Comment by kaloyan-raev** [comment]
I cannot reproduce the issue with syncthing.

Could you try running gateway with the `--log.stack` flag? I believe this flag will now print the stack trace wit the details.

**Comment by D4rk4** [comment]
Here is stack log:
```
2020-04-15T11:01:15.979Z        ERROR   gateway error:  {"error": "Not Implemented"}
storj.io/gateway/miniogw.(*layerLogging).log
        /go/src/storj.io/storj/miniogw/logging.go:54
storj.io/gateway/miniogw.(*layerLogging).CopyObjectPart
        /go/src/storj.io/storj/miniogw/logging.go:149
github.com/minio/minio/cmd.objectAPIHandlers.CopyObjectPartHandler
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/object-handlers.go:1854
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.httpTraceAll.func1
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/handler-utils.go:342
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.collectAPIStats.func1
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/handler-utils.go:402
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.maxClients.func1
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/handler-utils.go:366
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/gorilla/mux.(*Router).ServeHTTP
        /go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:748
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:763
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:624
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:608
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:544
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:68
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:93
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/crossdomain-xml-handler.go:51
github.com/minio/minio/cmd.redirectHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:247
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:315
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:274
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:385
github.com/rs/cors.(*Cors).Handler.func1
        /go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.resourceHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:525
github.com/minio/minio/cmd.authHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/auth-handler.go:450
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:798
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:136
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/generic-handlers.go:780
github.com/minio/minio/cmd/http.(*Server).Start.func1
        /go/pkg/mod/github.com/minio/minio@v0.0.0-20200402193522-ab66b2319490/cmd/http/server.go:104
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2007
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1890

```

**Comment by kaloyan-raev** [comment]
Thanks for the detailed stack log.

I spend some more time on testing. We will implement this missing `CopyObjectPartHandler` method, but unfortunately, other problems will hit independent of this one.

The way syncthing is copying files is that it first create a temp file with `.syncthing` prefix. After the file is completely copied this temp file is renamed to the expected file name. The problem is that we still haven't implemented server-side rename of objects yet. The effect of this is that renaming involves 1) downloading the object; 2) uploading the object with the new name; 3) deleting the object with the old name. This is very inefficient, especially with larger files, and leads to really bad user experiences in your case.

We are currently discussing if we can prioritize implementing the server-side rename as it affects other use cases too. I will write here when I have any update.

**Comment by acsfer** [comment]
As this somehow progressed almost 2 years later?

**Comment by halkyon** [comment]
> Has this somehow progressed almost 2 years later?

There is currently work underway implementing server-side copy as we speak, but for the moment you can use s3ql with the latest Gateway-ST version, with the caveat of less than ideal efficiency as Kaloyan pointed out in a previous comment. I gave it a go yesterday and it appears to work as expected.
